/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as anonymousLoginRouteImport } from './routes/(anonymous)/login'
import { Route as anonymousForget_passowrdRouteImport } from './routes/(anonymous)/forget_passowrd'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as authenticatedDashboardTagsIndexRouteImport } from './routes/(authenticated)/dashboard/tags/index'
import { Route as authenticatedDashboardSettingsIndexRouteImport } from './routes/(authenticated)/dashboard/settings/index'
import { Route as authenticatedDashboardServicesIndexRouteImport } from './routes/(authenticated)/dashboard/services/index'
import { Route as authenticatedDashboardProfileIndexRouteImport } from './routes/(authenticated)/dashboard/profile/index'
import { Route as authenticatedDashboardProductsIndexRouteImport } from './routes/(authenticated)/dashboard/products/index'
import { Route as authenticatedDashboardOrdersIndexRouteImport } from './routes/(authenticated)/dashboard/orders/index'
import { Route as authenticatedDashboardDiscountsIndexRouteImport } from './routes/(authenticated)/dashboard/discounts/index'
import { Route as authenticatedDashboardCategoriesIndexRouteImport } from './routes/(authenticated)/dashboard/categories/index'
import { Route as authenticatedDashboardAttributesIndexRouteImport } from './routes/(authenticated)/dashboard/attributes/index'
import { Route as authenticatedDashboardCategoriesEditRouteImport } from './routes/(authenticated)/dashboard/categories/edit'
import { Route as authenticatedDashboardCategoriesAddRouteImport } from './routes/(authenticated)/dashboard/categories/add'
import { Route as authenticatedDashboardAttributesEditRouteImport } from './routes/(authenticated)/dashboard/attributes/edit'
import { Route as authenticatedDashboardAttributesAddRouteImport } from './routes/(authenticated)/dashboard/attributes/add'

const anonymousLoginRoute = anonymousLoginRouteImport.update({
  id: '/(anonymous)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const anonymousForget_passowrdRoute =
  anonymousForget_passowrdRouteImport.update({
    id: '/(anonymous)/forget_passowrd',
    path: '/forget_passowrd',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/(authenticated)/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardTagsIndexRoute =
  authenticatedDashboardTagsIndexRouteImport.update({
    id: '/tags/',
    path: '/tags/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardSettingsIndexRoute =
  authenticatedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardServicesIndexRoute =
  authenticatedDashboardServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardProfileIndexRoute =
  authenticatedDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardProductsIndexRoute =
  authenticatedDashboardProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardOrdersIndexRoute =
  authenticatedDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardDiscountsIndexRoute =
  authenticatedDashboardDiscountsIndexRouteImport.update({
    id: '/discounts/',
    path: '/discounts/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardCategoriesIndexRoute =
  authenticatedDashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAttributesIndexRoute =
  authenticatedDashboardAttributesIndexRouteImport.update({
    id: '/attributes/',
    path: '/attributes/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardCategoriesEditRoute =
  authenticatedDashboardCategoriesEditRouteImport.update({
    id: '/categories/edit',
    path: '/categories/edit',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardCategoriesAddRoute =
  authenticatedDashboardCategoriesAddRouteImport.update({
    id: '/categories/add',
    path: '/categories/add',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAttributesEditRoute =
  authenticatedDashboardAttributesEditRouteImport.update({
    id: '/attributes/edit',
    path: '/attributes/edit',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAttributesAddRoute =
  authenticatedDashboardAttributesAddRouteImport.update({
    id: '/attributes/add',
    path: '/attributes/add',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/forget_passowrd': typeof anonymousForget_passowrdRoute
  '/login': typeof anonymousLoginRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/dashboard/attributes/add': typeof authenticatedDashboardAttributesAddRoute
  '/dashboard/attributes/edit': typeof authenticatedDashboardAttributesEditRoute
  '/dashboard/categories/add': typeof authenticatedDashboardCategoriesAddRoute
  '/dashboard/categories/edit': typeof authenticatedDashboardCategoriesEditRoute
  '/dashboard/attributes/': typeof authenticatedDashboardAttributesIndexRoute
  '/dashboard/categories/': typeof authenticatedDashboardCategoriesIndexRoute
  '/dashboard/discounts/': typeof authenticatedDashboardDiscountsIndexRoute
  '/dashboard/orders/': typeof authenticatedDashboardOrdersIndexRoute
  '/dashboard/products/': typeof authenticatedDashboardProductsIndexRoute
  '/dashboard/profile/': typeof authenticatedDashboardProfileIndexRoute
  '/dashboard/services/': typeof authenticatedDashboardServicesIndexRoute
  '/dashboard/settings/': typeof authenticatedDashboardSettingsIndexRoute
  '/dashboard/tags/': typeof authenticatedDashboardTagsIndexRoute
}
export interface FileRoutesByTo {
  '/forget_passowrd': typeof anonymousForget_passowrdRoute
  '/login': typeof anonymousLoginRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/dashboard/attributes/add': typeof authenticatedDashboardAttributesAddRoute
  '/dashboard/attributes/edit': typeof authenticatedDashboardAttributesEditRoute
  '/dashboard/categories/add': typeof authenticatedDashboardCategoriesAddRoute
  '/dashboard/categories/edit': typeof authenticatedDashboardCategoriesEditRoute
  '/dashboard/attributes': typeof authenticatedDashboardAttributesIndexRoute
  '/dashboard/categories': typeof authenticatedDashboardCategoriesIndexRoute
  '/dashboard/discounts': typeof authenticatedDashboardDiscountsIndexRoute
  '/dashboard/orders': typeof authenticatedDashboardOrdersIndexRoute
  '/dashboard/products': typeof authenticatedDashboardProductsIndexRoute
  '/dashboard/profile': typeof authenticatedDashboardProfileIndexRoute
  '/dashboard/services': typeof authenticatedDashboardServicesIndexRoute
  '/dashboard/settings': typeof authenticatedDashboardSettingsIndexRoute
  '/dashboard/tags': typeof authenticatedDashboardTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(anonymous)/forget_passowrd': typeof anonymousForget_passowrdRoute
  '/(anonymous)/login': typeof anonymousLoginRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(authenticated)/dashboard/attributes/add': typeof authenticatedDashboardAttributesAddRoute
  '/(authenticated)/dashboard/attributes/edit': typeof authenticatedDashboardAttributesEditRoute
  '/(authenticated)/dashboard/categories/add': typeof authenticatedDashboardCategoriesAddRoute
  '/(authenticated)/dashboard/categories/edit': typeof authenticatedDashboardCategoriesEditRoute
  '/(authenticated)/dashboard/attributes/': typeof authenticatedDashboardAttributesIndexRoute
  '/(authenticated)/dashboard/categories/': typeof authenticatedDashboardCategoriesIndexRoute
  '/(authenticated)/dashboard/discounts/': typeof authenticatedDashboardDiscountsIndexRoute
  '/(authenticated)/dashboard/orders/': typeof authenticatedDashboardOrdersIndexRoute
  '/(authenticated)/dashboard/products/': typeof authenticatedDashboardProductsIndexRoute
  '/(authenticated)/dashboard/profile/': typeof authenticatedDashboardProfileIndexRoute
  '/(authenticated)/dashboard/services/': typeof authenticatedDashboardServicesIndexRoute
  '/(authenticated)/dashboard/settings/': typeof authenticatedDashboardSettingsIndexRoute
  '/(authenticated)/dashboard/tags/': typeof authenticatedDashboardTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forget_passowrd'
    | '/login'
    | '/dashboard/'
    | '/dashboard/attributes/add'
    | '/dashboard/attributes/edit'
    | '/dashboard/categories/add'
    | '/dashboard/categories/edit'
    | '/dashboard/attributes/'
    | '/dashboard/categories/'
    | '/dashboard/discounts/'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/profile/'
    | '/dashboard/services/'
    | '/dashboard/settings/'
    | '/dashboard/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forget_passowrd'
    | '/login'
    | '/dashboard'
    | '/dashboard/attributes/add'
    | '/dashboard/attributes/edit'
    | '/dashboard/categories/add'
    | '/dashboard/categories/edit'
    | '/dashboard/attributes'
    | '/dashboard/categories'
    | '/dashboard/discounts'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/tags'
  id:
    | '__root__'
    | '/(authenticated)/dashboard'
    | '/(anonymous)/forget_passowrd'
    | '/(anonymous)/login'
    | '/(authenticated)/dashboard/'
    | '/(authenticated)/dashboard/attributes/add'
    | '/(authenticated)/dashboard/attributes/edit'
    | '/(authenticated)/dashboard/categories/add'
    | '/(authenticated)/dashboard/categories/edit'
    | '/(authenticated)/dashboard/attributes/'
    | '/(authenticated)/dashboard/categories/'
    | '/(authenticated)/dashboard/discounts/'
    | '/(authenticated)/dashboard/orders/'
    | '/(authenticated)/dashboard/products/'
    | '/(authenticated)/dashboard/profile/'
    | '/(authenticated)/dashboard/services/'
    | '/(authenticated)/dashboard/settings/'
    | '/(authenticated)/dashboard/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
  anonymousForget_passowrdRoute: typeof anonymousForget_passowrdRoute
  anonymousLoginRoute: typeof anonymousLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(anonymous)/login': {
      id: '/(anonymous)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof anonymousLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(anonymous)/forget_passowrd': {
      id: '/(anonymous)/forget_passowrd'
      path: '/forget_passowrd'
      fullPath: '/forget_passowrd'
      preLoaderRoute: typeof anonymousForget_passowrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/tags/': {
      id: '/(authenticated)/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags/'
      preLoaderRoute: typeof authenticatedDashboardTagsIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/settings/': {
      id: '/(authenticated)/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof authenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/services/': {
      id: '/(authenticated)/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services/'
      preLoaderRoute: typeof authenticatedDashboardServicesIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/profile/': {
      id: '/(authenticated)/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof authenticatedDashboardProfileIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/products/': {
      id: '/(authenticated)/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof authenticatedDashboardProductsIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/orders/': {
      id: '/(authenticated)/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof authenticatedDashboardOrdersIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/discounts/': {
      id: '/(authenticated)/dashboard/discounts/'
      path: '/discounts'
      fullPath: '/dashboard/discounts/'
      preLoaderRoute: typeof authenticatedDashboardDiscountsIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/categories/': {
      id: '/(authenticated)/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof authenticatedDashboardCategoriesIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/attributes/': {
      id: '/(authenticated)/dashboard/attributes/'
      path: '/attributes'
      fullPath: '/dashboard/attributes/'
      preLoaderRoute: typeof authenticatedDashboardAttributesIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/categories/edit': {
      id: '/(authenticated)/dashboard/categories/edit'
      path: '/categories/edit'
      fullPath: '/dashboard/categories/edit'
      preLoaderRoute: typeof authenticatedDashboardCategoriesEditRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/categories/add': {
      id: '/(authenticated)/dashboard/categories/add'
      path: '/categories/add'
      fullPath: '/dashboard/categories/add'
      preLoaderRoute: typeof authenticatedDashboardCategoriesAddRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/attributes/edit': {
      id: '/(authenticated)/dashboard/attributes/edit'
      path: '/attributes/edit'
      fullPath: '/dashboard/attributes/edit'
      preLoaderRoute: typeof authenticatedDashboardAttributesEditRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/attributes/add': {
      id: '/(authenticated)/dashboard/attributes/add'
      path: '/attributes/add'
      fullPath: '/dashboard/attributes/add'
      preLoaderRoute: typeof authenticatedDashboardAttributesAddRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
  }
}

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
  authenticatedDashboardAttributesAddRoute: typeof authenticatedDashboardAttributesAddRoute
  authenticatedDashboardAttributesEditRoute: typeof authenticatedDashboardAttributesEditRoute
  authenticatedDashboardCategoriesAddRoute: typeof authenticatedDashboardCategoriesAddRoute
  authenticatedDashboardCategoriesEditRoute: typeof authenticatedDashboardCategoriesEditRoute
  authenticatedDashboardAttributesIndexRoute: typeof authenticatedDashboardAttributesIndexRoute
  authenticatedDashboardCategoriesIndexRoute: typeof authenticatedDashboardCategoriesIndexRoute
  authenticatedDashboardDiscountsIndexRoute: typeof authenticatedDashboardDiscountsIndexRoute
  authenticatedDashboardOrdersIndexRoute: typeof authenticatedDashboardOrdersIndexRoute
  authenticatedDashboardProductsIndexRoute: typeof authenticatedDashboardProductsIndexRoute
  authenticatedDashboardProfileIndexRoute: typeof authenticatedDashboardProfileIndexRoute
  authenticatedDashboardServicesIndexRoute: typeof authenticatedDashboardServicesIndexRoute
  authenticatedDashboardSettingsIndexRoute: typeof authenticatedDashboardSettingsIndexRoute
  authenticatedDashboardTagsIndexRoute: typeof authenticatedDashboardTagsIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
    authenticatedDashboardAttributesAddRoute:
      authenticatedDashboardAttributesAddRoute,
    authenticatedDashboardAttributesEditRoute:
      authenticatedDashboardAttributesEditRoute,
    authenticatedDashboardCategoriesAddRoute:
      authenticatedDashboardCategoriesAddRoute,
    authenticatedDashboardCategoriesEditRoute:
      authenticatedDashboardCategoriesEditRoute,
    authenticatedDashboardAttributesIndexRoute:
      authenticatedDashboardAttributesIndexRoute,
    authenticatedDashboardCategoriesIndexRoute:
      authenticatedDashboardCategoriesIndexRoute,
    authenticatedDashboardDiscountsIndexRoute:
      authenticatedDashboardDiscountsIndexRoute,
    authenticatedDashboardOrdersIndexRoute:
      authenticatedDashboardOrdersIndexRoute,
    authenticatedDashboardProductsIndexRoute:
      authenticatedDashboardProductsIndexRoute,
    authenticatedDashboardProfileIndexRoute:
      authenticatedDashboardProfileIndexRoute,
    authenticatedDashboardServicesIndexRoute:
      authenticatedDashboardServicesIndexRoute,
    authenticatedDashboardSettingsIndexRoute:
      authenticatedDashboardSettingsIndexRoute,
    authenticatedDashboardTagsIndexRoute: authenticatedDashboardTagsIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
  anonymousForget_passowrdRoute: anonymousForget_passowrdRoute,
  anonymousLoginRoute: anonymousLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
