/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appanonymousLoginRouteImport } from './routes/(app)/(anonymous)/login'
import { Route as appanonymousForget_passowrdRouteImport } from './routes/(app)/(anonymous)/forget_passowrd'
import { Route as appauthenticatedDashboardRouteRouteImport } from './routes/(app)/(authenticated)/dashboard/route'
import { Route as appauthenticatedDashboardIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/index'
import { Route as appauthenticatedDashboardTagsIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/tags/index'
import { Route as appauthenticatedDashboardSettingsIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/settings/index'
import { Route as appauthenticatedDashboardServicesIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/services/index'
import { Route as appauthenticatedDashboardProfileIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/profile/index'
import { Route as appauthenticatedDashboardProductsIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/products/index'
import { Route as appauthenticatedDashboardOrdersIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/orders/index'
import { Route as appauthenticatedDashboardDiscountsIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/discounts/index'
import { Route as appauthenticatedDashboardCategoriesIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/categories/index'
import { Route as appauthenticatedDashboardAttributesIndexRouteImport } from './routes/(app)/(authenticated)/dashboard/attributes/index'
import { Route as appauthenticatedDashboardCategoriesEditRouteImport } from './routes/(app)/(authenticated)/dashboard/categories/edit'
import { Route as appauthenticatedDashboardCategoriesAddRouteImport } from './routes/(app)/(authenticated)/dashboard/categories/add'
import { Route as appauthenticatedDashboardAttributesEditRouteImport } from './routes/(app)/(authenticated)/dashboard/attributes/edit'
import { Route as appauthenticatedDashboardAttributesAddRouteImport } from './routes/(app)/(authenticated)/dashboard/attributes/add'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appanonymousLoginRoute = appanonymousLoginRouteImport.update({
  id: '/(anonymous)/login',
  path: '/login',
  getParentRoute: () => appRouteRoute,
} as any)
const appanonymousForget_passowrdRoute =
  appanonymousForget_passowrdRouteImport.update({
    id: '/(anonymous)/forget_passowrd',
    path: '/forget_passowrd',
    getParentRoute: () => appRouteRoute,
  } as any)
const appauthenticatedDashboardRouteRoute =
  appauthenticatedDashboardRouteRouteImport.update({
    id: '/(authenticated)/dashboard',
    path: '/dashboard',
    getParentRoute: () => appRouteRoute,
  } as any)
const appauthenticatedDashboardIndexRoute =
  appauthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardTagsIndexRoute =
  appauthenticatedDashboardTagsIndexRouteImport.update({
    id: '/tags/',
    path: '/tags/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardSettingsIndexRoute =
  appauthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardServicesIndexRoute =
  appauthenticatedDashboardServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardProfileIndexRoute =
  appauthenticatedDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardProductsIndexRoute =
  appauthenticatedDashboardProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardOrdersIndexRoute =
  appauthenticatedDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardDiscountsIndexRoute =
  appauthenticatedDashboardDiscountsIndexRouteImport.update({
    id: '/discounts/',
    path: '/discounts/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardCategoriesIndexRoute =
  appauthenticatedDashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardAttributesIndexRoute =
  appauthenticatedDashboardAttributesIndexRouteImport.update({
    id: '/attributes/',
    path: '/attributes/',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardCategoriesEditRoute =
  appauthenticatedDashboardCategoriesEditRouteImport.update({
    id: '/categories/edit',
    path: '/categories/edit',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardCategoriesAddRoute =
  appauthenticatedDashboardCategoriesAddRouteImport.update({
    id: '/categories/add',
    path: '/categories/add',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardAttributesEditRoute =
  appauthenticatedDashboardAttributesEditRouteImport.update({
    id: '/attributes/edit',
    path: '/attributes/edit',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)
const appauthenticatedDashboardAttributesAddRoute =
  appauthenticatedDashboardAttributesAddRouteImport.update({
    id: '/attributes/add',
    path: '/attributes/add',
    getParentRoute: () => appauthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/dashboard': typeof appauthenticatedDashboardRouteRouteWithChildren
  '/forget_passowrd': typeof appanonymousForget_passowrdRoute
  '/login': typeof appanonymousLoginRoute
  '/dashboard/': typeof appauthenticatedDashboardIndexRoute
  '/dashboard/attributes/add': typeof appauthenticatedDashboardAttributesAddRoute
  '/dashboard/attributes/edit': typeof appauthenticatedDashboardAttributesEditRoute
  '/dashboard/categories/add': typeof appauthenticatedDashboardCategoriesAddRoute
  '/dashboard/categories/edit': typeof appauthenticatedDashboardCategoriesEditRoute
  '/dashboard/attributes/': typeof appauthenticatedDashboardAttributesIndexRoute
  '/dashboard/categories/': typeof appauthenticatedDashboardCategoriesIndexRoute
  '/dashboard/discounts/': typeof appauthenticatedDashboardDiscountsIndexRoute
  '/dashboard/orders/': typeof appauthenticatedDashboardOrdersIndexRoute
  '/dashboard/products/': typeof appauthenticatedDashboardProductsIndexRoute
  '/dashboard/profile/': typeof appauthenticatedDashboardProfileIndexRoute
  '/dashboard/services/': typeof appauthenticatedDashboardServicesIndexRoute
  '/dashboard/settings/': typeof appauthenticatedDashboardSettingsIndexRoute
  '/dashboard/tags/': typeof appauthenticatedDashboardTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/forget_passowrd': typeof appanonymousForget_passowrdRoute
  '/login': typeof appanonymousLoginRoute
  '/dashboard': typeof appauthenticatedDashboardIndexRoute
  '/dashboard/attributes/add': typeof appauthenticatedDashboardAttributesAddRoute
  '/dashboard/attributes/edit': typeof appauthenticatedDashboardAttributesEditRoute
  '/dashboard/categories/add': typeof appauthenticatedDashboardCategoriesAddRoute
  '/dashboard/categories/edit': typeof appauthenticatedDashboardCategoriesEditRoute
  '/dashboard/attributes': typeof appauthenticatedDashboardAttributesIndexRoute
  '/dashboard/categories': typeof appauthenticatedDashboardCategoriesIndexRoute
  '/dashboard/discounts': typeof appauthenticatedDashboardDiscountsIndexRoute
  '/dashboard/orders': typeof appauthenticatedDashboardOrdersIndexRoute
  '/dashboard/products': typeof appauthenticatedDashboardProductsIndexRoute
  '/dashboard/profile': typeof appauthenticatedDashboardProfileIndexRoute
  '/dashboard/services': typeof appauthenticatedDashboardServicesIndexRoute
  '/dashboard/settings': typeof appauthenticatedDashboardSettingsIndexRoute
  '/dashboard/tags': typeof appauthenticatedDashboardTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(app)/(authenticated)/dashboard': typeof appauthenticatedDashboardRouteRouteWithChildren
  '/(app)/(anonymous)/forget_passowrd': typeof appanonymousForget_passowrdRoute
  '/(app)/(anonymous)/login': typeof appanonymousLoginRoute
  '/(app)/(authenticated)/dashboard/': typeof appauthenticatedDashboardIndexRoute
  '/(app)/(authenticated)/dashboard/attributes/add': typeof appauthenticatedDashboardAttributesAddRoute
  '/(app)/(authenticated)/dashboard/attributes/edit': typeof appauthenticatedDashboardAttributesEditRoute
  '/(app)/(authenticated)/dashboard/categories/add': typeof appauthenticatedDashboardCategoriesAddRoute
  '/(app)/(authenticated)/dashboard/categories/edit': typeof appauthenticatedDashboardCategoriesEditRoute
  '/(app)/(authenticated)/dashboard/attributes/': typeof appauthenticatedDashboardAttributesIndexRoute
  '/(app)/(authenticated)/dashboard/categories/': typeof appauthenticatedDashboardCategoriesIndexRoute
  '/(app)/(authenticated)/dashboard/discounts/': typeof appauthenticatedDashboardDiscountsIndexRoute
  '/(app)/(authenticated)/dashboard/orders/': typeof appauthenticatedDashboardOrdersIndexRoute
  '/(app)/(authenticated)/dashboard/products/': typeof appauthenticatedDashboardProductsIndexRoute
  '/(app)/(authenticated)/dashboard/profile/': typeof appauthenticatedDashboardProfileIndexRoute
  '/(app)/(authenticated)/dashboard/services/': typeof appauthenticatedDashboardServicesIndexRoute
  '/(app)/(authenticated)/dashboard/settings/': typeof appauthenticatedDashboardSettingsIndexRoute
  '/(app)/(authenticated)/dashboard/tags/': typeof appauthenticatedDashboardTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forget_passowrd'
    | '/login'
    | '/dashboard/'
    | '/dashboard/attributes/add'
    | '/dashboard/attributes/edit'
    | '/dashboard/categories/add'
    | '/dashboard/categories/edit'
    | '/dashboard/attributes/'
    | '/dashboard/categories/'
    | '/dashboard/discounts/'
    | '/dashboard/orders/'
    | '/dashboard/products/'
    | '/dashboard/profile/'
    | '/dashboard/services/'
    | '/dashboard/settings/'
    | '/dashboard/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forget_passowrd'
    | '/login'
    | '/dashboard'
    | '/dashboard/attributes/add'
    | '/dashboard/attributes/edit'
    | '/dashboard/categories/add'
    | '/dashboard/categories/edit'
    | '/dashboard/attributes'
    | '/dashboard/categories'
    | '/dashboard/discounts'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/tags'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/'
    | '/(app)/(authenticated)/dashboard'
    | '/(app)/(anonymous)/forget_passowrd'
    | '/(app)/(anonymous)/login'
    | '/(app)/(authenticated)/dashboard/'
    | '/(app)/(authenticated)/dashboard/attributes/add'
    | '/(app)/(authenticated)/dashboard/attributes/edit'
    | '/(app)/(authenticated)/dashboard/categories/add'
    | '/(app)/(authenticated)/dashboard/categories/edit'
    | '/(app)/(authenticated)/dashboard/attributes/'
    | '/(app)/(authenticated)/dashboard/categories/'
    | '/(app)/(authenticated)/dashboard/discounts/'
    | '/(app)/(authenticated)/dashboard/orders/'
    | '/(app)/(authenticated)/dashboard/products/'
    | '/(app)/(authenticated)/dashboard/profile/'
    | '/(app)/(authenticated)/dashboard/services/'
    | '/(app)/(authenticated)/dashboard/settings/'
    | '/(app)/(authenticated)/dashboard/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(anonymous)/login': {
      id: '/(app)/(anonymous)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appanonymousLoginRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(anonymous)/forget_passowrd': {
      id: '/(app)/(anonymous)/forget_passowrd'
      path: '/forget_passowrd'
      fullPath: '/forget_passowrd'
      preLoaderRoute: typeof appanonymousForget_passowrdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(authenticated)/dashboard': {
      id: '/(app)/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appauthenticatedDashboardRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(authenticated)/dashboard/': {
      id: '/(app)/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appauthenticatedDashboardIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/tags/': {
      id: '/(app)/(authenticated)/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags/'
      preLoaderRoute: typeof appauthenticatedDashboardTagsIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/settings/': {
      id: '/(app)/(authenticated)/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof appauthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/services/': {
      id: '/(app)/(authenticated)/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services/'
      preLoaderRoute: typeof appauthenticatedDashboardServicesIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/profile/': {
      id: '/(app)/(authenticated)/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof appauthenticatedDashboardProfileIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/products/': {
      id: '/(app)/(authenticated)/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof appauthenticatedDashboardProductsIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/orders/': {
      id: '/(app)/(authenticated)/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof appauthenticatedDashboardOrdersIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/discounts/': {
      id: '/(app)/(authenticated)/dashboard/discounts/'
      path: '/discounts'
      fullPath: '/dashboard/discounts/'
      preLoaderRoute: typeof appauthenticatedDashboardDiscountsIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/categories/': {
      id: '/(app)/(authenticated)/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof appauthenticatedDashboardCategoriesIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/attributes/': {
      id: '/(app)/(authenticated)/dashboard/attributes/'
      path: '/attributes'
      fullPath: '/dashboard/attributes/'
      preLoaderRoute: typeof appauthenticatedDashboardAttributesIndexRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/categories/edit': {
      id: '/(app)/(authenticated)/dashboard/categories/edit'
      path: '/categories/edit'
      fullPath: '/dashboard/categories/edit'
      preLoaderRoute: typeof appauthenticatedDashboardCategoriesEditRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/categories/add': {
      id: '/(app)/(authenticated)/dashboard/categories/add'
      path: '/categories/add'
      fullPath: '/dashboard/categories/add'
      preLoaderRoute: typeof appauthenticatedDashboardCategoriesAddRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/attributes/edit': {
      id: '/(app)/(authenticated)/dashboard/attributes/edit'
      path: '/attributes/edit'
      fullPath: '/dashboard/attributes/edit'
      preLoaderRoute: typeof appauthenticatedDashboardAttributesEditRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
    '/(app)/(authenticated)/dashboard/attributes/add': {
      id: '/(app)/(authenticated)/dashboard/attributes/add'
      path: '/attributes/add'
      fullPath: '/dashboard/attributes/add'
      preLoaderRoute: typeof appauthenticatedDashboardAttributesAddRouteImport
      parentRoute: typeof appauthenticatedDashboardRouteRoute
    }
  }
}

interface appauthenticatedDashboardRouteRouteChildren {
  appauthenticatedDashboardIndexRoute: typeof appauthenticatedDashboardIndexRoute
  appauthenticatedDashboardAttributesAddRoute: typeof appauthenticatedDashboardAttributesAddRoute
  appauthenticatedDashboardAttributesEditRoute: typeof appauthenticatedDashboardAttributesEditRoute
  appauthenticatedDashboardCategoriesAddRoute: typeof appauthenticatedDashboardCategoriesAddRoute
  appauthenticatedDashboardCategoriesEditRoute: typeof appauthenticatedDashboardCategoriesEditRoute
  appauthenticatedDashboardAttributesIndexRoute: typeof appauthenticatedDashboardAttributesIndexRoute
  appauthenticatedDashboardCategoriesIndexRoute: typeof appauthenticatedDashboardCategoriesIndexRoute
  appauthenticatedDashboardDiscountsIndexRoute: typeof appauthenticatedDashboardDiscountsIndexRoute
  appauthenticatedDashboardOrdersIndexRoute: typeof appauthenticatedDashboardOrdersIndexRoute
  appauthenticatedDashboardProductsIndexRoute: typeof appauthenticatedDashboardProductsIndexRoute
  appauthenticatedDashboardProfileIndexRoute: typeof appauthenticatedDashboardProfileIndexRoute
  appauthenticatedDashboardServicesIndexRoute: typeof appauthenticatedDashboardServicesIndexRoute
  appauthenticatedDashboardSettingsIndexRoute: typeof appauthenticatedDashboardSettingsIndexRoute
  appauthenticatedDashboardTagsIndexRoute: typeof appauthenticatedDashboardTagsIndexRoute
}

const appauthenticatedDashboardRouteRouteChildren: appauthenticatedDashboardRouteRouteChildren =
  {
    appauthenticatedDashboardIndexRoute: appauthenticatedDashboardIndexRoute,
    appauthenticatedDashboardAttributesAddRoute:
      appauthenticatedDashboardAttributesAddRoute,
    appauthenticatedDashboardAttributesEditRoute:
      appauthenticatedDashboardAttributesEditRoute,
    appauthenticatedDashboardCategoriesAddRoute:
      appauthenticatedDashboardCategoriesAddRoute,
    appauthenticatedDashboardCategoriesEditRoute:
      appauthenticatedDashboardCategoriesEditRoute,
    appauthenticatedDashboardAttributesIndexRoute:
      appauthenticatedDashboardAttributesIndexRoute,
    appauthenticatedDashboardCategoriesIndexRoute:
      appauthenticatedDashboardCategoriesIndexRoute,
    appauthenticatedDashboardDiscountsIndexRoute:
      appauthenticatedDashboardDiscountsIndexRoute,
    appauthenticatedDashboardOrdersIndexRoute:
      appauthenticatedDashboardOrdersIndexRoute,
    appauthenticatedDashboardProductsIndexRoute:
      appauthenticatedDashboardProductsIndexRoute,
    appauthenticatedDashboardProfileIndexRoute:
      appauthenticatedDashboardProfileIndexRoute,
    appauthenticatedDashboardServicesIndexRoute:
      appauthenticatedDashboardServicesIndexRoute,
    appauthenticatedDashboardSettingsIndexRoute:
      appauthenticatedDashboardSettingsIndexRoute,
    appauthenticatedDashboardTagsIndexRoute:
      appauthenticatedDashboardTagsIndexRoute,
  }

const appauthenticatedDashboardRouteRouteWithChildren =
  appauthenticatedDashboardRouteRoute._addFileChildren(
    appauthenticatedDashboardRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appauthenticatedDashboardRouteRoute: typeof appauthenticatedDashboardRouteRouteWithChildren
  appanonymousForget_passowrdRoute: typeof appanonymousForget_passowrdRoute
  appanonymousLoginRoute: typeof appanonymousLoginRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appauthenticatedDashboardRouteRoute:
    appauthenticatedDashboardRouteRouteWithChildren,
  appanonymousForget_passowrdRoute: appanonymousForget_passowrdRoute,
  appanonymousLoginRoute: appanonymousLoginRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
